[package]
name = "server_puzzle"
version = "0.1.0"
authors = ["jessai <maya.jessai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
